package com.example.x_b.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.x_b.DatasBean;
import com.example.x_b.BooleanBean;

import com.example.x_b.db.DatasBeanDao;
import com.example.x_b.db.BooleanBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig datasBeanDaoConfig;
    private final DaoConfig booleanBeanDaoConfig;

    private final DatasBeanDao datasBeanDao;
    private final BooleanBeanDao booleanBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        datasBeanDaoConfig = daoConfigMap.get(DatasBeanDao.class).clone();
        datasBeanDaoConfig.initIdentityScope(type);

        booleanBeanDaoConfig = daoConfigMap.get(BooleanBeanDao.class).clone();
        booleanBeanDaoConfig.initIdentityScope(type);

        datasBeanDao = new DatasBeanDao(datasBeanDaoConfig, this);
        booleanBeanDao = new BooleanBeanDao(booleanBeanDaoConfig, this);

        registerDao(DatasBean.class, datasBeanDao);
        registerDao(BooleanBean.class, booleanBeanDao);
    }
    
    public void clear() {
        datasBeanDaoConfig.clearIdentityScope();
        booleanBeanDaoConfig.clearIdentityScope();
    }

    public DatasBeanDao getDatasBeanDao() {
        return datasBeanDao;
    }

    public BooleanBeanDao getBooleanBeanDao() {
        return booleanBeanDao;
    }

}
